services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\FaqT3demo\:
    resource: '../Classes/*'

  B13\FaqT3demo\Controller\FaqController:
    public: true

  B13\FaqT3demo\Hooks\DataHandlerCacheHook:
    public: true
    arguments:
      $cachePages: '@cache.pages'

  B13\FaqT3demo\RecordList\DatabaseRecordList:
    public: true
