base: 'https://typo3.finanztip.test/'

errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=29'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=49'
  -
    errorCode: 500
    errorHandler: Page
    errorContentSource: 't3://page?uid=50'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
    solr_core_read: core_en
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ltr
    flag: de
    websiteTitle: ''
    fallbackType: strict
    fallbacks: ''
    solr_core_read: core_de
  -
    title: 'עִברִית'
    enabled: true
    base: /he/
    typo3Language: he
    locale: he_IL.UTF-8
    iso-639-1: he
    websiteTitle: ''
    navigationTitle: HE
    hreflang: he
    direction: rtl
    fallbackType: strict
    fallbacks: ''
    flag: il
    languageId: 2
    solr_enabled_read: false
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      resettimer.html: 1603464133342
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n\r\nSitemap: https://demo.typo3.org/sitemap.xml"
  -
    route: google34eb0c66f374609a.html
    type: staticText
    content: 'google-site-verification: google34eb0c66f374609a.html'
sitePackage: site_t3demo
solr_enabled_read: true
solr_host_read: '%env(SOLR_HOST)%'
solr_path_read: /
solr_port_read: '%env(SOLR_PORT)%'
solr_scheme_read: '%env(SOLR_SCHEME)%'
solr_use_write_connection: false
websiteTitle: ''
